//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_DBFirst_23022022
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hesaplar
    {
        public int id { get; set; }
        public string HesapAdi { get; set; }
        public Nullable<decimal> Bakiye { get; set; }
    }
}
