//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_DBFirst_23022022
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KuzeyYeliEntities : DbContext
    {
        public KuzeyYeliEntities()
            : base("name=KuzeyYeliEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bolge> Bolges { get; set; }
        public virtual DbSet<Bolgeler> Bolgelers { get; set; }
        public virtual DbSet<Hesaplar> Hesaplars { get; set; }
        public virtual DbSet<Kategoriler> Kategorilers { get; set; }
        public virtual DbSet<MusteriDemographic> MusteriDemographics { get; set; }
        public virtual DbSet<Musteriler> Musterilers { get; set; }
        public virtual DbSet<Nakliyeciler> Nakliyecilers { get; set; }
        public virtual DbSet<Personel> Personels { get; set; }
        public virtual DbSet<Personeller> Personellers { get; set; }
        public virtual DbSet<SatisDetay> SatisDetays { get; set; }
        public virtual DbSet<Satislar> Satislars { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tedarikciler> Tedarikcilers { get; set; }
        public virtual DbSet<Urunler> Urunlers { get; set; }
        public virtual DbSet<deneme> denemes { get; set; }
    }
}
